project_id = "alpudhhsmgtpmgpjfuqs"

[analytics]
enabled = false

[functions.validate-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.submit-application]
verify_jwt = false

[functions.update-application-status]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.rate-limited-auth]
verify_jwt = false