// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'; 
import type { Database } from './types';

// Defaults to production values. Override with environment variables for local development.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://alpudhhsmgtpmgpjfuqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "sb_publishable_x9j94wxK7OqIvyNh0eN5hw_uCBviZiZ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // OAuth PKCE exchange runs only in OAuthCallback (avoid double exchange)
    detectSessionInUrl: false,
    flowType: 'pkce',
  }
});







