// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'; 
import type { Database } from './types';

// No fallback values: the build must provide these, otherwise a production
// build could silently point at the wrong Supabase project.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY. Set them in the build environment (.env locally, Coolify env vars in production)."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // OAuth PKCE exchange runs only in OAuthCallback (avoid double exchange)
    detectSessionInUrl: false,
    flowType: 'pkce',
  }
});







