// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpkpnfpepobtsgzroqjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwa3BuZnBlcG9idHNnenJvcWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODc3MTQsImV4cCI6MjA3MTg2MzcxNH0.IyuBDF0M08is3GSrUhdef_qdIcH50KmXRletU3qrZgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});